/**
 * Fix duplicate exports generated by bun build.
 * Removes trailing single-line `export { ... };` when the same
 * symbols are already exported by a prior block.
 */
import { readdir, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";

const distDir = join(import.meta.dir, "..", "dist");
const files = await readdir(distDir);

function parseExportNames(line: string): Set<string> | null {
  const match = line.match(/^export\s*\{([^}]+)\}\s*;?\s*$/);
  if (!match) return null;
  const names = match[1]!.split(",").map((s) => s.trim()).filter(Boolean);
  return new Set(names);
}

for (const file of files) {
  if (!file.endsWith(".js")) continue;

  const path = join(distDir, file);
  const content = await readFile(path, "utf-8");
  const lines = content.split("\n");

  // First pass: collect all exported names from multi-line export blocks
  const exportedNames = new Set<string>();
  let inBlock = false;

  for (const line of lines) {
    const trimmed = line.trim();
    if (trimmed.startsWith("export {") && !trimmed.endsWith("};")) {
      inBlock = true;
      continue;
    }
    if (inBlock) {
      if (trimmed.endsWith("};")) {
        // Last line of block, extract names
        const name = trimmed.replace("};", "").trim();
        if (name) exportedNames.add(name.replace(/,$/, "").trim());
        inBlock = false;
      } else {
        // Middle of block
        const name = trimmed.replace(/,$/, "").trim();
        if (name) exportedNames.add(name);
      }
    }
  }

  // Second pass: remove single-line export statements whose names are all already exported
  const cleaned: string[] = [];
  for (const line of lines) {
    const trimmed = line.trim();
    if (trimmed.startsWith("export {") && trimmed.endsWith("};")) {
      const names = parseExportNames(trimmed);
      if (names && names.size > 0 && [...names].every((n) => exportedNames.has(n))) {
        continue; // skip — all names already exported
      }
    }
    cleaned.push(line);
  }

  const result = cleaned.join("\n");
  if (result !== content) {
    await writeFile(path, result);
    console.log(`Fixed: ${file}`);
  }
}

console.log("Done.");
